"""simpleBoard table

Revision ID: 20734d7e5c59
Revises: 
Create Date: 2020-04-07 03:39:11.653241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20734d7e5c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_content', sa.String(length=100), nullable=False),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_content', sa.String(length=100), nullable=False),
    sa.Column('replied_date', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('post')
    # ### end Alembic commands ###
